name: build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.19' ]

    steps:
      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Set up podman and start as *cough* daemon
        run: |
          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          sudo apt update
          sudo apt install podman
          sudo systemctl enable podman.socket
          sudo systemctl start podman.socket

      - name: Set up podman dev dependencies
        run: |
          sudo apt-get -y install \
            build-essential pkg-config libbtrfs-dev libgpgme-dev

      - name: Set up Go for root
        run: |
          sudo ln -sf `which go` `sudo which go` || true
          sudo go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Test Go packages
        run: go test -v -p 1 -tags
          exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper,libdm_no_deferred_remove
          -exec sudo ./...
